### ISSUE TITLE
WebOptimizer throws FileNotFoundException instead of allowing 404 status to be returned

### ISSUE THREAD

**Issue by rodoch** [ligershark/WebOptimizer#102]
Possibly related to #72.

This issue arises out of an experience I had with a reasonably high-traffic website that was frequently polled (by search engine crawlers, presumably) for static files from earlier versions of the site that no longer exist. 

The expected behaviour would be that such requests receive a 404 HTTP status code in response.  However, with WebOptimizer in place a System.IO.FileNotFoundException is thrown when the middleware fails to find the static asset and a 500 error response is returned instead. The full stack trace is provided below. In this particular case this behaviour led to a lot of error logs and alerts for what is normally a well-understood and unproblematic usage pattern. It would be desirable that WebOptimizer could catch the exception and return a 404 response in such cases, or be configured to do so.

I appreciate there may be reasons why the current behaviour is as it is, and perhaps it is difficult to disambiguate the above case from other I/O issues. If so, that's fine. Potentially, applications implementing WebOptimizer could mitigate the issue by putting appropriate redirects in place (though this is not always trivial) or, as in my case, by using a glob pattern to limit the scope of files processed by the WebOptimizer pipeline. However, if this could be handled by WebOptimizer itself I think a lot of users might benefit.

Thanks for the great package!
Ronan

```c#
System.IO.FileNotFoundException: No files found matching "/template-screen.css" exist in "<FILE-PATH-REDACTED>"
   at WebOptimizer.Asset.ExpandGlobs(IAsset asset, IHostingEnvironment env)
   at WebOptimizer.Asset.GenerateCacheKey(HttpContext context)
   at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 86
   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)

Full Trace:

   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by abhishekbhalani** [comment]
@rodoch 
Is it resolved?

**Comment by rodoch** [comment]
There has been no activity on this issue so I don't think so.

**Comment by abhishekbhalani** [comment]
@rodoch thanks. It is resolved at my end..

**Comment by puhnastik** [comment]
Up. Anybody can pick it up?
