### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\mysite\myapp\obj\WebOptimizerCache' is denied.

### ISSUE THREAD

**Issue by VictorioBerra** [ligershark/WebOptimizer#166]
This happens during IIS cold starts.

- dotnet core 5
- IIS
- `<PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.304" />`
- `<PackageReference Include="LigerShark.WebOptimizer.Sass" Version="3.0.43-beta" />`

## Startup - WebOpt Configuration

```csharp
return services.AddWebOptimizer(pipeline =>
        {
            // Main css bundle (pre-minified files)
            pipeline
                .AddCssBundle(
                    "/css/bundle.min.css",
                    "/lib/datatables/css/dataTables.bootstrap4.min.css",
                    "/lib/datatables.net-buttons-bs4/buttons.bootstrap4.css");

            // Main js bundle (pre-minified files)
            pipeline
                .AddJavaScriptBundle(
                    "/js/bundle.min.js",
                    "/lib/jszip/jszip.min.js", // Dependency for Datatables excel export Button
                    "/lib/pdfmake/pdfmake.min.js", // Dependency for Datatables pdf export Button
                    "/lib/pdfmake/vfs_fonts.min.js", // Dependency for Datatables pdf export Button
                    "/lib/jquery/jquery.min.js",
                    "/lib/jquery-validation/dist/jquery.validate.min.js",
                    "/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js",
                    "/lib/bootstrap/dist/js/bootstrap.min.js",
                    "/lib/datatables/js/jquery.dataTables.min.js",
                    "/lib/datatables-buttons/js/dataTables.buttons.min.js",
                    "/lib/datatables-buttons/js/buttons.html5.min.js",
                    "/lib/datatables-buttons/js/buttons.print.min.js",
                    "/lib/datatables.net-buttons-bs4/buttons.bootstrap4.min.js",
                    "/lib/datatables/js/dataTables.bootstrap4.min.js");

            // Nested bundles would be great.
            // https://github.com/ligershark/WebOptimizer/issues/159
            // IE bundle up all the pre-minified stuff above, and then minify some additional files with WebOptimizer and concatenate it all together.
            pipeline
                .MinifyJsFiles("/js/site.js");
            pipeline
            .MinifyCssFiles("/css/site.css");

            // Enable referencing .scss files directly in the browser (http://domain/a.scss)
            pipeline.CompileScssFiles();

            // Take our custom Bootstrap SCSS and compile+minify it.
            pipeline
            .AddScssBundle("/css/bootstrap.custom.min.css", "css/bootstrap.custom.scss")
            .MinifyCss();
        });
```

## Startup - Configure

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseSecurityHeaders();

    app.UseWebOptimizer();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
    }

    app.UseStaticFiles();

    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();

    app.UseCustomSerilogRequestLogging();

    app.UseMiniProfiler();

    app.UseEndpoints(endpoints =>
    {
        endpoints
            .MapRazorPages()
            .RequireAuthorization();
    });
}
```

## Error

```
Exception: System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\mysite\myapp\obj\WebOptimizerCache' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at WebOptimizer.AssetResponseStore.AddAsync(String bucket, String cachekey, AssetResponse assetResponse)
   at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHeadersMiddleware.cs:line 68
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**Comment by VictorioBerra** [comment]
It appears that setting `enableDiskCache` to `false` fixes the issue. Does it make sense to do that?

**Comment by nvirth** [comment]
I think the default for `cacheDirectory` is invalid. [It points into the web app's content root](https://github.com/ligershark/WebOptimizer/blob/master/src/WebOptimizer.Core/WebOptimizerConfig.cs#L40) ([If later fixed, I've found it in this commit](https://github.com/ligershark/WebOptimizer/blob/cd44f7cbff7a45ed4555ba2a9412f5713f86ffbb/src/WebOptimizer.Core/WebOptimizerConfig.cs#L40)
)

A production web application should not have write access on its own directory, that would open security concerns.
To add write access only to the default `<contentRoot>/obj` folder would need the deployment set up properly.
That's unnecessary extra work.
Why not just use the web application's temp folder?

**Comment by VictorioBerra** [comment]
@nvirth Do web apps have temp folders they can write to by default in IIS?

**Comment by nvirth** [comment]
I think yes. But I'm not sure. But then I can't remember setting up any folder credentials for `HttpPostedFileBase` to work in the old ASP.NET MVC. That saves the uploaded files into a temporary folder - maybe it's the `Temporary ASP.NET Files` folder somewhere, don't really know that.

Anyway, I just fixed the issue in my project with a custom `IConfigureOptions<WebOptimizerOptions>` implementation - calling `services.AddTransient<MyWebOptimzerOptions>` after `services.AddWebOptimizer()` to override the default options. In this `MyWebOptimzerOptions` I set `CacheDirectory` to `Path.GetTempPath()`. Seems to work so far...

**Comment by nvirth** [comment]
@VictorioBerra `Path.GetTempPath()` does not always work. On one of our new test servers, we've seen this log now: System.UnauthorizedAccessException: Access to the path 'C:\Windows\TEMP' is denied.

**Comment by thibnes** [comment]
We also experience the same issue.

**Comment by yodasad** [comment]
Why does `AssetReponseStore` depend on `IConfigureOptions<WebOptimizerOptions>` and not on `IOptions<WebOptimizerOptions>`?

**Comment by danielgreen** [comment]
Seeing the same error as the OP, for an ASP.NET 8 web app running in IIS, WebOptimizer version 3.0.405

**Comment by moxplod** [comment]
What's the fix for this in .net 8? Web app running on azure app service linux

**Comment by nthornton2010** [comment]
Same error here, using latest WebOptimizer on .NET 8. We're not getting it on cold start, we're getting it randomly when the cache is being accessed (but not always).

**Comment by TomasMalecek** [comment]
To see the configuration, I added this in my Program.cs:

```
var logger = app.Services.GetRequiredService<ILogger<Program>>();
var options = app.Services.GetRequiredService<IOptions<WebOptimizerOptions>>().Value;
logger.LogInformation("Web Optimizer cache directory: {Path}", options.CacheDirectory);
```

When I configure the middleware using:

```
builder.Services.AddWebOptimizer(
    pipeline => BundleConfig.RegisterBundles(pipeline, builder.Environment.IsDevelopment()))
```

I get `C:\Work\MyRepo\MyProject\obj\WebOptimizerCache` in Visual Studio and something like `C:\inetpub\wwwroot\MySite\obj\WebOptimizerCache` when the app is actually deployed to run in IIS.

When I add another lambda parameter configuring the options...

```
builder.Services.AddWebOptimizer(
    pipeline => BundleConfig.RegisterBundles(pipeline, builder.Environment.IsDevelopment()),
    options => options.CacheDirectory = Directory.CreateTempSubdirectory("WebOptimizerCache").FullName)
```

... I get for example `C:\WINDOWS\TEMP\WebOptimizerCacheqygcnwg0.tab`. This holds both when the app pool is configured to use the IIS app pool identity and when it is configured to run as NETWORK SERVICE.

Directory.CreateTempSubdirectory() is available since .NET 7+.

I wish the configuration I use is the default as it better reflects security practices and should work much more often.
