### ISSUE TITLE
Change in LinkTagHelper.Process broke my app

### ISSUE THREAD

**Issue by timheuer** [ligershark/WebOptimizer#197]
It would appear that this change: https://github.com/ligershark/WebOptimizer/commit/326e3819a6b8d8353441e37df211c615d69f57da#diff-a1fafee7a645789d31d1695c9fb77ca5303ffd659546bdb34374a2da493d1ae1R49 broke my app.  Updating to the latest package I have an exception at this code:

```
<meta name="description" content="@ViewData["Description"]" />
```

That throws:
```
   at WebOptimizer.Taghelpers.LinkTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCoreGeneratedDocument.Views_Shared__Layout.<>c__DisplayClass68_0.<<ExecuteAsync>b__0>d.MoveNext() in C:\Users\timheuer\source\projects\blog-timheuer\Views\Shared\_Layout.cshtml:line 26
```

![image](https://user-images.githubusercontent.com/4821/141041233-d69c9f6a-9112-4137-9c2f-4e565c1f6200.png)

Rolling back to 3.0.319 no longer repros this error and updating to latest reproduces it.

**Comment by timheuer** [comment]
@exileDev
