### ISSUE TITLE
AddCssBundle works fine in .NET 5 but fails in .NET 6

### ISSUE THREAD

**Issue by boeschenstein** [ligershark/WebOptimizer#200]
Hello

AddCssBundle works fine in .NET 5 but fails in .NET 6.

What I do:

`pipeline.AddCssBundle("/css/bundle.css", "css/site.css");`

The error I see (you need to do a hard refresh in the browser: Ctrl-F5): https://localhost:44392/css/bundle.css

```
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at WebOptimizer.CssFingerprinter.Adjust(String content, IFileInfo input, IWebHostEnvironment env)
   at WebOptimizer.CssFingerprinter.ExecuteAsync(IAssetContext config)
   at WebOptimizer.Asset.ExecuteAsync(HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I can see the original file in the browser: https://localhost:44392/css/site.css

Versions:
- WebOptimizer 3.0.330
- .NET SDK Version: 6.0.100
- Visual Studio 2022

**Comment by NicolaiJee** [comment]
I have the exact same error.

**Comment by d-sky** [comment]
The same for me

**Comment by zoinkydoink** [comment]
when will this pr be part next nuget?
i have this issue and using nuget 3.0.344

**Comment by madskristensen** [comment]
3.0.344 is the latest code, so there is no code in this repo that is not currently in that released version

**Comment by zoinkydoink** [comment]
@madskristensen latest fails using .NET 6 then, had to revert back to a local cloned project described here https://github.com/ligershark/WebOptimizer/issues/210

**Comment by Acruval** [comment]
Hello I am getting this problem in 3.1 too. (And in 6.01 of course. I create an app for each ### one.
the only diference in 3.1 I am not getting the v parameter
<link href="/css/bundle.css?v=**5lDIMl5BhDQ2EWREQE-DOshGUO4**" rel="stylesheet" />
Just say even the page can work
 pipeline.AddCssBundle("/css/bundle.css", "css/site.css"); break the default minimize
so at the moment I use just
services.AddWebOptimizer();
Cheers
