### ISSUE TITLE
AssetPipeline.TryGetAssetFromRoute: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by AlexBar** [ligershark/WebOptimizer#66]
Time to time I'm getting the following exception when trying to access the page that uses a script by  globing pattern:

```csharp
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at WebOptimizer.AssetPipeline.TryGetAssetFromRoute(String route, IAsset& asset) in D:\XXXXXXXXXXX\WebOptimizer.Core\AssetPipeline.cs:line 39
   at WebOptimizer.Taghelpers.ScriptTagHelper.Process(TagHelperContext context, TagHelperOutput output) in D:\XXXXXXXXXXX\WebOptimizer.Core\Taghelpers\ScriptTagHelper.cs:line 39
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore._XXXXXXXXXXXXXXX___cshtml.<ExecuteAsync>d__14.MoveNext() in XXXXXXXXXXX.cshtml:line 0
```

To reproduce it I tried to open a few pages (~10 pages at once) after project build (clear cache and reload all tabs).

**Comment by bergkampx360** [comment]
Same issue here. After the server restarting, sometimes the first request (which tries to load multiple javascript files into the page) fails and throws the next exception:

```
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at WebOptimizer.AssetPipeline.TryGetAssetFromRoute(String route, IAsset& asset)
   at WebOptimizer.AssetMiddleware.InvokeAsync(HttpContext context, IOptionsSnapshot`1 options)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

WebOptimizer version: 1.0.236

**Comment by lahma** [comment]
Created https://github.com/ligershark/WebOptimizer/pull/141 to fix this concurrency issue.
